exclude: '^$'
fail_fast: true 
repos:
  -   repo: https://github.com/Yelp/detect-secrets
      rev: v1.5.0
      hooks:
      -   id: detect-secrets
          name: Detect secrets
          language: python
          entry: detect-secrets-hook
          args: [
            '--baseline', 
            '.secrets.baseline',
            '--exclude-files',
            '(_test\.go$|/testdata/)',
            ]
  -   repo: https://github.com/sqlfluff/sqlfluff 
      rev: 3.2.4
      hooks:
      -   id: sqlfluff-fix
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
      -   id: check-json
      -   id: check-merge-conflict
      -   id: check-yaml
